import React from 'react';
import { motion } from 'framer-motion';
import { BrainCircuit, LineChart, Target } from 'lucide-react';
import Hero from '../components/Hero';

// Animation variants for the container
const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.2,
      delayChildren: 0.3,
    },
  },
};

// Animation variants for individual cards
const cardVariants = {
  hidden: { y: 40, opacity: 0 },
  visible: {
    y: 0,
    opacity: 1,
    transition: { type: 'spring', stiffness: 100, damping: 12 },
  },
};

const Home = () => {
  const features = [
    {
      title: 'Predictive Analytics',
      desc: 'Identify future academic decline before it becomes critical using deep-learning neural networks.',
      icon: <LineChart className="w-8 h-8 text-blue-400" />,
      gradient: 'from-blue-500/20 to-cyan-500/0',
    },
    {
      title: 'Behavior Tracking',
      desc: 'Real-time analysis of attendance, engagement, and progression metrics via biometric data points.',
      icon: <Target className="w-8 h-8 text-purple-400" />,
      gradient: 'from-purple-500/20 to-pink-500/0',
    },
    {
      title: 'AI Recommendations',
      desc: 'Hyper-personalized interventions and adaptive learning strategies generated by GPT-4 class models.',
      icon: <BrainCircuit className="w-8 h-8 text-emerald-400" />,
      gradient: 'from-emerald-500/20 to-teal-500/0',
    },
  ];

  return (
    <div className="relative min-h-screen overflow-hidden bg-[#020617] text-white">
      {/* Animated Background Blobs */}
      <div className="absolute top-0 left-0 w-full h-full -z-10">
        <div className="absolute top-[-10%] left-[-10%] w-[500px] h-[500px] rounded-full bg-blue-600/10 blur-[120px] animate-pulse" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[500px] h-[500px] rounded-full bg-purple-600/10 blur-[120px] animate-pulse" />
      </div>

      <Hero />

      <motion.section
        variants={containerVariants}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: "-100px" }}
        className="relative z-10 mx-auto grid max-w-7xl gap-8 px-6 py-32 md:grid-cols-3"
      >
        {features.map((feature, index) => (
          <motion.div
            key={index}
            variants={cardVariants}
            whileHover={{ 
              scale: 1.05, 
              translateY: -10,
              boxShadow: "0 20px 40px rgba(0,0,0,0.4)" 
            }}
            className="group relative overflow-hidden rounded-[2.5rem] border border-white/10 bg-white/5 p-10 backdrop-blur-xl transition-all duration-300"
          >
            {/* Inner Glow Effect */}
            <div className={`absolute inset-0 bg-gradient-to-br ${feature.gradient} opacity-0 group-hover:opacity-100 transition-opacity duration-500`} />
            
            <div className="relative z-10">
              <div className="mb-6 inline-flex rounded-2xl bg-white/5 p-4 ring-1 ring-white/10 group-hover:ring-white/20 transition-all">
                {feature.icon}
              </div>
              
              <h2 className="mb-4 text-2xl font-bold tracking-tight group-hover:text-transparent group-hover:bg-clip-text group-hover:bg-gradient-to-r group-hover:from-white group-hover:to-white/50">
                {feature.title}
              </h2>
              
              <p className="leading-relaxed text-slate-400 group-hover:text-slate-200 transition-colors">
                {feature.desc}
              </p>

              {/* Decorative line */}
              <div className="mt-8 h-1 w-12 rounded-full bg-white/10 group-hover:w-full group-hover:bg-gradient-to-r group-hover:from-blue-500 group-hover:to-purple-500 transition-all duration-500" />
            </div>
          </motion.div>
        ))}
      </motion.section>

      {/* CSS for custom animations */}
      <style jsx>{`
        @keyframes pulse {
          0%, 100% { opacity: 0.1; transform: scale(1); }
          50% { opacity: 0.15; transform: scale(1.1); }
        }
        .animate-pulse {
          animation: pulse 8s cubic-bezier(0.4, 0, 0.6, 1) infinite;
        }
      `}</style>
    </div>
  );
};

export default Home;